---
# tasks file for fact_ansi
- name: Prints various Ansible facts
  ansible.builtin.debug:
    msg: 
      - Les caractéristiques de la machine {{ ansible_hostname }} sont les suivantes:\
      - le nom de domaine conplet :{{ ansible_facts.fqdn }}
      - l'adress IPv4 principale :{{ ansible_facts.default_ipv4.address }}  
      - la distribution :{{ ansible_facts['distribution'] }}
      - version :{{ ansible_facts['distribution_version'] }}        
      - la liste des interfaces réseau :{{ ansible_interfaces }} 
      - la liste des serveurs DNS :{{ ansible_dns['nameservers'] }}
      - la version du noyau :{{ ansible_kernel }}
  
